//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Grib.Api.Interop.SWIG {

public class CodesBufrHeader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CodesBufrHeader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CodesBufrHeader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CodesBufrHeader() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GribApiProxyPINVOKE.delete_CodesBufrHeader(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint messageOffset {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_messageOffset_set(swigCPtr, value);
    } 
    get {
      uint ret = GribApiProxyPINVOKE.CodesBufrHeader_messageOffset_get(swigCPtr);
      return ret;
    } 
  }

  public uint messageSize {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_messageSize_set(swigCPtr, value);
    } 
    get {
      uint ret = GribApiProxyPINVOKE.CodesBufrHeader_messageSize_get(swigCPtr);
      return ret;
    } 
  }

  public int edition {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_edition_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_edition_get(swigCPtr);
      return ret;
    } 
  }

  public int masterTableNumber {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_masterTableNumber_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_masterTableNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int bufrHeaderSubCentre {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_bufrHeaderSubCentre_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_bufrHeaderSubCentre_get(swigCPtr);
      return ret;
    } 
  }

  public int bufrHeaderCentre {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_bufrHeaderCentre_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_bufrHeaderCentre_get(swigCPtr);
      return ret;
    } 
  }

  public int updateSequenceNumber {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_updateSequenceNumber_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_updateSequenceNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int dataCategory {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_dataCategory_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_dataCategory_get(swigCPtr);
      return ret;
    } 
  }

  public int dataSubCategory {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_dataSubCategory_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_dataSubCategory_get(swigCPtr);
      return ret;
    } 
  }

  public int masterTablesVersionNumber {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_masterTablesVersionNumber_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_masterTablesVersionNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int localTablesVersionNumber {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localTablesVersionNumber_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localTablesVersionNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalYear {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalYear_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalYear_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalMonth {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalMonth_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalMonth_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalDay {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalDay_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalDay_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalHour {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalHour_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalHour_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalMinute {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalMinute_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalMinute_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalSecond {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalSecond_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalSecond_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalDate {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalDate_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalDate_get(swigCPtr);
      return ret;
    } 
  }

  public int typicalTime {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_typicalTime_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_typicalTime_get(swigCPtr);
      return ret;
    } 
  }

  public int internationalDataSubCategory {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_internationalDataSubCategory_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_internationalDataSubCategory_get(swigCPtr);
      return ret;
    } 
  }

  public int localSectionPresent {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localSectionPresent_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localSectionPresent_get(swigCPtr);
      return ret;
    } 
  }

  public int ecmwfLocalSectionPresent {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_ecmwfLocalSectionPresent_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_ecmwfLocalSectionPresent_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbType {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbType_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbType_get(swigCPtr);
      return ret;
    } 
  }

  public int oldSubtype {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_oldSubtype_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_oldSubtype_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbSubtype {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbSubtype_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbSubtype_get(swigCPtr);
      return ret;
    } 
  }

  public string ident {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_ident_set(swigCPtr, value);
    } 
    get {
      string ret = GribApiProxyPINVOKE.CodesBufrHeader_ident_get(swigCPtr);
      return ret;
    } 
  }

  public int localYear {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localYear_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localYear_get(swigCPtr);
      return ret;
    } 
  }

  public int localMonth {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localMonth_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localMonth_get(swigCPtr);
      return ret;
    } 
  }

  public int localDay {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localDay_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localDay_get(swigCPtr);
      return ret;
    } 
  }

  public int localHour {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localHour_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localHour_get(swigCPtr);
      return ret;
    } 
  }

  public int localMinute {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localMinute_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localMinute_get(swigCPtr);
      return ret;
    } 
  }

  public int localSecond {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localSecond_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localSecond_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbtimeDay {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeDay_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeDay_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbtimeHour {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeHour_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeHour_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbtimeMinute {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeMinute_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeMinute_get(swigCPtr);
      return ret;
    } 
  }

  public int rdbtimeSecond {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeSecond_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rdbtimeSecond_get(swigCPtr);
      return ret;
    } 
  }

  public int rectimeDay {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rectimeDay_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rectimeDay_get(swigCPtr);
      return ret;
    } 
  }

  public int rectimeHour {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rectimeHour_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rectimeHour_get(swigCPtr);
      return ret;
    } 
  }

  public int rectimeMinute {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rectimeMinute_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rectimeMinute_get(swigCPtr);
      return ret;
    } 
  }

  public int rectimeSecond {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_rectimeSecond_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_rectimeSecond_get(swigCPtr);
      return ret;
    } 
  }

  public int isSatellite {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_isSatellite_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_isSatellite_get(swigCPtr);
      return ret;
    } 
  }

  public double localLongitude1 {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLongitude1_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLongitude1_get(swigCPtr);
      return ret;
    } 
  }

  public double localLatitude1 {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLatitude1_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLatitude1_get(swigCPtr);
      return ret;
    } 
  }

  public double localLongitude2 {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLongitude2_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLongitude2_get(swigCPtr);
      return ret;
    } 
  }

  public double localLatitude2 {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLatitude2_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLatitude2_get(swigCPtr);
      return ret;
    } 
  }

  public double localLatitude {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLatitude_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLatitude_get(swigCPtr);
      return ret;
    } 
  }

  public double localLongitude {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localLongitude_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.CodesBufrHeader_localLongitude_get(swigCPtr);
      return ret;
    } 
  }

  public int localNumberOfObservations {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_localNumberOfObservations_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_localNumberOfObservations_get(swigCPtr);
      return ret;
    } 
  }

  public int satelliteID {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_satelliteID_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_satelliteID_get(swigCPtr);
      return ret;
    } 
  }

  public int qualityControl {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_qualityControl_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_qualityControl_get(swigCPtr);
      return ret;
    } 
  }

  public int newSubtype {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_newSubtype_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_newSubtype_get(swigCPtr);
      return ret;
    } 
  }

  public int daLoop {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_daLoop_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_daLoop_get(swigCPtr);
      return ret;
    } 
  }

  public uint numberOfSubsets {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_numberOfSubsets_set(swigCPtr, value);
    } 
    get {
      uint ret = GribApiProxyPINVOKE.CodesBufrHeader_numberOfSubsets_get(swigCPtr);
      return ret;
    } 
  }

  public int observedData {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_observedData_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_observedData_get(swigCPtr);
      return ret;
    } 
  }

  public int compressedData {
    set {
      GribApiProxyPINVOKE.CodesBufrHeader_compressedData_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.CodesBufrHeader_compressedData_get(swigCPtr);
      return ret;
    } 
  }

  public CodesBufrHeader() : this(GribApiProxyPINVOKE.new_CodesBufrHeader(), true) {
  }

}

}
